version: '3'

services:
  mysql:
    image: mysql:8.0.33
    # restart: always
    container_name: bank_system_mysql8
    environment:
      MYSQL_ROOT_PASSWORD: test
    ports:
      - 3306:3306
    volumes:
      - ./dockerDB/mysql:/var/lib/docker/volumes/mysql_data